config/routes.rb
Geonotifications::Application.routes.draw do
  devise_for :users
  resources :pois
  resources :aois

  root 'home#index'

  

end

app/models/aoi.rb
class Aoi
  include Mongoid::Document

  field :locations, type: Array
  field :title, type: String
  field :categories, type: Array

  belongs_to :user
  has_and_belongs_to_many :discovered_pois, class_name: 'Poi'

end

app/models/poi.rb
class Poi
  include Mongoid::Document
  field :location, type: Array
  field :category, type: String
  field :title, type: String
  field :description, type: String

  belongs_to :created_by, class_name: 'User'

  validates :location, presence: true, length: {is: 2 }
  validates :category, presence: true
  index({ location: "2d" }, { min: -200, max: 200 })
  index({ category: 1})

  def latitude
    location[0] if location
  end

  def longitude
    location[1] if location
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  field :name, type: String
  validates :name, presence: true
  has_many :pois, inverse_of: :created_by
  has_many :aois



  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  ## Token authenticatable
  # field :authentication_token, type: String



end

app/controllers/aois_controller.rb
class AoisController < ApplicationController
  before_action :authenticate_user!
  respond_to :json, :html

  def index
    @aoi = current_user.aois
    respond_with @aoi
  end

  def create
    area = params.require(:area).permit(:title, locations: [])
    area[:locations] = area[:locations].collect do |loc|
      loc.split(',').map(&:to_f)
    end

    aoi = Aoi.new(area)
    aoi.user = current_user

    if aoi.save
      redirect_to root_url
    else
      raise "invalid aoi"
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @aoi = Aoi.new
  end
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_poi, only: [:show, :edit, :update, :destroy]

  respond_to :json, :html
  # GET /pois
  def index
    @pois = Poi.all
    respond_with @pois
  end

  # GET /pois/1
  def show
    respond_with @poi
  end

  # GET /pois/new
  def new
    @poi = Poi.new
    respond_with @poi
  end

  # GET /pois/1/edit
  def edit
    respond_with @poi
  end

  # POST /pois
  def create
    @poi = Poi.new(poi_params)
    @poi.created_by = current_user

    if @poi.save
      redirect_to @poi, notice: 'Poi was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /pois/1
  def update
    if @poi.update(poi_params)
      redirect_to @poi, notice: 'Poi was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /pois/1
  def destroy
    @poi.destroy
    redirect_to pois_url, notice: 'Poi was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poi
      @poi = Poi.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def poi_params
      params[:poi][:location] = [params[:poi].delete(:longitude), params[:poi].delete(:latitude)]
      params.require(:poi).permit(:location, :category, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">

    <div class="col col-lg-9 col-sm-9">
      <div id="map-container">

      </div>
    </div>

    <div id="toolbar" class="col col-lg-3 col-sm-3">
      <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
          <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
      <div id="areas-container">
        <%= form_tag '/aois' do -%>
            <div id="areas">

            </div>
            <p>
              <%= submit_tag "Save areas", id: 'save-areas' %>
            </p>
        <% end -%>
      </div>

      <div id="poi-container">
        <% if user_signed_in? %>
            <%= link_to 'Create POI', new_poi_path  %>
        <% end %>
      </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geonotifications</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDcIZPf3Cc0gRAXNss5v7KfhFAiAxIiBWg&sensor=false&libraries=drawing" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<% if user_signed_in? %>
<body class="connected">
<% else %>
<body>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<header class="navbar">
  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <a href="#" class="navbar-brand">Geonotifications</a>
        </div>
    </div>
  </div>
</header>

    <%= yield %>
<script src="http://localhost:1337/livereload.js"></script>
</body>
</html>

app/views/pois/_form.html.erb
<%= form_for(@poi) do |f| %>
  <% if @poi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poi.errors.count, "error") %> prohibited this poi from being saved:</h2>

      <ul>
      <% @poi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pois/edit.html.erb
<h1>Editing poi</h1>

<%= render 'form' %>

<%= link_to 'Show', @poi %> |
<%= link_to 'Back', pois_path %>

app/views/pois/index.html.erb
<h1>Listing pois</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Category</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pois.each do |poi| %>
      <tr>
        <td><%= poi.location %></td>
        <td><%= poi.category %></td>
        <td><%= poi.title %></td>
        <td><%= poi.description %></td>
        <td><%= link_to 'Show', poi %></td>
        <td><%= link_to 'Edit', edit_poi_path(poi) %></td>
        <td><%= link_to 'Destroy', poi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poi', new_poi_path %>

app/views/pois/new.html.erb
<h1>New poi</h1>

<%= render 'form' %>

<%= link_to 'Back', pois_path %>

app/views/pois/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @poi.location %>
</p>

<p>
  <strong>Category:</strong>
  <%= @poi.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @poi.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @poi.description %>
</p>

<%= link_to 'Edit', edit_poi_path(@poi) %> |
<%= link_to 'Back', pois_path %>